apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-wordpress-svc
  labels:
    app: wordpress
spec:
  ports:
    - port: {{.Values.port}}
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None