apiVersion: apps/v1
kind: StatefullSet
metadata:
  name: {{.Release.Name}}-mysql
  labels:
    app: wordpress
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: {{.Values.image}}:{{Values.tag}}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: {{.Values.port}}
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{.Release.Name}}-mysql-pv-claim