apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: {{.Values.port}}
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer